import { ApprovalRequestPropsSchema, ButtonGroupPropsSchema, ConfirmationPropsSchema, ErrorNoticePropsSchema, FileAttachmentPropsSchema, FormPropsSchema, LinkCardPropsSchema, ProgressPropsSchema, SourceListPropsSchema, TablePropsSchema, ToolCallPropsSchema, createComponentInteraction, resolveComponentFrame, validateStandardComponentInteraction, type ComponentManifest } from '@agentskit/chat'
import type { ComponentInteractionEvent, ComponentRenderFrame } from '@agentskit/chat-protocol'
import { useState, type ReactElement } from 'react'
import { Pressable, Text, TextInput, View } from 'react-native'

export interface StandardComponentNativeProps { readonly frame: ComponentRenderFrame; readonly manifest: ComponentManifest; readonly onInteract: (event: ComponentInteractionEvent) => void; readonly disabled?: boolean }
const Button = ({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean | undefined }): ReactElement => <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress}><Text>{label}</Text></Pressable>

const StandardFormNative = (props: StandardComponentNativeProps): ReactElement => {
  const item = FormPropsSchema.parse(props.frame.props)
  const [values, setValues] = useState<Readonly<Record<string, string | boolean>>>({})
  return <View accessibilityRole="none" accessibilityLabel={item.title ?? 'Form'} testID="ak-form">{item.title ? <Text accessibilityRole="header">{item.title}</Text> : null}{item.fields.map(field => <View key={field.id}><Text>{field.label}</Text>{field.type === 'checkbox' ? <Button label={`${field.label}: ${values[field.id] ? 'checked' : 'unchecked'}`} disabled={props.disabled} onPress={() => setValues(current => ({ ...current, [field.id]: !current[field.id] }))} /> : field.type === 'select' ? <View accessibilityRole="radiogroup" accessibilityLabel={field.label}>{field.options?.map(option => <Pressable key={option.id} accessibilityRole="radio" accessibilityState={{ checked: values[field.id] === option.id }} disabled={props.disabled} onPress={() => setValues(current => ({ ...current, [field.id]: option.id }))}><Text>{values[field.id] === option.id ? '●' : '○'} {option.label}</Text></Pressable>)}</View> : <TextInput accessibilityLabel={field.label} editable={!props.disabled} placeholder={field.placeholder} inputMode={field.type === 'email' ? 'email' : field.type === 'number' ? 'numeric' : 'text'} value={String(values[field.id] ?? '')} onChangeText={value => setValues(current => ({ ...current, [field.id]: value }))} />}</View>)}<Button label={item.submitLabel} disabled={props.disabled || !validateStandardComponentInteraction('form', item, 'submit', values)} onPress={() => props.onInteract(createComponentInteraction(props.frame, props.manifest, 'submit', values))} /></View>
}

export const StandardComponentNative = (props: StandardComponentNativeProps): ReactElement | null => {
  if (!resolveComponentFrame(props.frame, props.manifest).ok || props.frame.componentKey === 'choice-list') return null
  const emit = (event: string, value?: unknown): void => props.onInteract(createComponentInteraction(props.frame, props.manifest, event, value))
  const key = props.frame.componentKey
  if (key === 'button-group') { const item = ButtonGroupPropsSchema.parse(props.frame.props); return <View accessibilityRole="none" accessibilityLabel={item.label} testID="ak-button-group"><Text>{item.label}</Text>{item.buttons.map(button => <Button key={button.id} label={button.label} disabled={props.disabled || button.disabled} onPress={() => emit('select', button.id)} />)}</View> }
  if (key === 'form') return <StandardFormNative {...props} />
  if (key === 'confirmation') { const item = ConfirmationPropsSchema.parse(props.frame.props); return <View accessibilityLabel={item.title} testID="ak-confirmation"><Text>{item.title}</Text><Text>{item.message}</Text><Button label={item.confirmLabel} disabled={props.disabled} onPress={() => emit('confirm')} /><Button label={item.cancelLabel} disabled={props.disabled} onPress={() => emit('cancel')} /></View> }
  if (key === 'progress') { const item = ProgressPropsSchema.parse(props.frame.props); return <View accessibilityRole="progressbar" accessibilityLabel={item.label} accessibilityValue={{ min: 0, max: 100, now: item.value }} testID="ak-progress"><Text>{item.label}: {item.value}%</Text><Text>{item.status}</Text></View> }
  if (key === 'source-list') { const item = SourceListPropsSchema.parse(props.frame.props); return <View accessibilityRole="list" accessibilityLabel={item.label} testID="ak-source-list"><Text>{item.label}</Text>{item.sources.map(source => <View key={source.id}><Button label={source.title} disabled={!source.url || props.disabled} onPress={() => emit('open', source.id)} /><Text>{source.snippet}</Text></View>)}</View> }
  if (key === 'link-card') { const item = LinkCardPropsSchema.parse(props.frame.props); return <Pressable accessibilityRole="link" accessibilityLabel={item.label ?? item.title} disabled={props.disabled} onPress={() => emit('open', item.href)} testID="ak-link-card"><Text>{item.title}</Text><Text>{item.description}</Text></Pressable> }
  if (key === 'error-notice') { const item = ErrorNoticePropsSchema.parse(props.frame.props); return <View accessibilityRole="alert" testID="ak-error-notice"><Text>{item.title}</Text><Text>{item.message}</Text><Text>{item.code}</Text>{item.retryLabel ? <Button label={item.retryLabel} disabled={props.disabled} onPress={() => emit('retry')} /> : null}</View> }
  if (key === 'tool-call') { const item = ToolCallPropsSchema.parse(props.frame.props); return <View accessibilityRole="summary" accessibilityLabel={`${item.name}: ${item.status}`} testID="ak-tool-call"><Text>{item.name}</Text><Text>{item.status}</Text><Text>{item.arguments ? JSON.stringify(item.arguments) : ''}</Text><Text>{item.result === undefined ? '' : JSON.stringify(item.result)}</Text></View> }
  if (key === 'approval-request') { const item = ApprovalRequestPropsSchema.parse(props.frame.props); return <View accessibilityLabel={item.title} testID="ak-approval-request"><Text>{item.title}</Text><Text>{item.description}</Text><Button label={item.approveLabel} disabled={props.disabled} onPress={() => emit('approve')} /><Button label={item.denyLabel} disabled={props.disabled} onPress={() => emit('deny')} /></View> }
  if (key === 'table') { const item = TablePropsSchema.parse(props.frame.props); return <View accessibilityRole="summary" accessibilityLabel={item.caption} testID="ak-table"><Text>{item.caption}</Text><Text>{item.columns.map(column => column.label).join(' | ')}</Text>{item.rows.map((row, index) => <Text key={index}>{item.columns.map(column => String(row[column.key] ?? '')).join(' | ')}</Text>)}</View> }
  if (key === 'file-attachment') { const item = FileAttachmentPropsSchema.parse(props.frame.props); return <View accessibilityLabel={`${item.name}, ${item.mimeType}`} testID="ak-file-attachment"><Text>{item.name}</Text><Text>{item.mimeType}</Text><Text>{item.sizeBytes === undefined ? '' : `${item.sizeBytes} bytes`}</Text>{item.url ? <Button label="Open" disabled={props.disabled} onPress={() => emit('open', item.url)} /> : null}</View> }
  return null
}
