import { testChatConformance } from './chat-conformance'
import { expect, test } from '@playwright/test'

testChatConformance({ placeholder: 'Ask support or type /support', stopName: 'Stop' })

test('opens a support ticket only after confirmation', async ({ page }) => {
  await page.goto('/')
  const input = page.getByPlaceholder('Ask support or type /support')
  await input.fill('/support')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Open support ticket' }).click()
  await expect(page.getByRole('button', { name: 'Approve' })).toBeVisible()
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText(/SUP-1/)).toBeVisible()
})

test('completes and revises the deterministic onboarding reference', async ({ page }) => {
  await page.goto('/?reference=onboarding')
  const input = page.getByPlaceholder('Type /onboarding to begin')
  await input.fill('/onboarding')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByLabel('Primary role').selectOption('engineering')
  await page.getByLabel('First goal').fill('Automate handoffs')
  await page.getByRole('button', { name: 'Save answers' }).click()
  await input.fill('/recommend')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Revise answers' }).click()
  await input.fill('/revise')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await expect(page.getByRole('form', { name: 'Tell us how you work' }).last()).toBeVisible()
  await page.getByLabel('Primary role').last().selectOption('product')
  await page.getByLabel('First goal').last().fill('Plan releases')
  await page.getByRole('button', { name: 'Save answers' }).last().click()
  await input.fill('/recommend')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Use this setup' }).last().click()
  await input.fill('/accept')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Complete onboarding' }).click()
  await page.getByRole('button', { name: 'Approve' }).click()
  await input.fill('/done')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await expect(page.getByText('Onboarding complete. Your guided workspace is ready.')).toBeVisible()
})

test('reads status and confirms a policy-protected restart', async ({ page }) => {
  await page.goto('/?reference=operations')
  const input = page.getByPlaceholder('Type /operations to begin')
  await input.fill('/operations')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Read status' }).click()
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText(/checkout-api is healthy/)).toBeVisible()
  await input.fill('/operations')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Restart operation' }).last().click()
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText(/checkout-api restarted/)).toBeVisible()
})

test('denies an unauthorized operations proposal', async ({ page }) => {
  await page.goto('/?reference=operations-unauthorized')
  const input = page.getByPlaceholder('Type /operations to begin')
  await input.fill('/operations')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await page.getByRole('button', { name: 'Restart operation' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByText(/restarted/)).toHaveCount(0)
})

test('renders grounded RAG sources and a deterministic no-results state', async ({ page }) => {
  await page.goto('/?reference=rag')
  const input = page.getByPlaceholder('Ask a grounded question')
  await input.fill('How does AgentsKit Chat work?')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await expect(page.getByText('AgentsKit Chat overview')).toBeVisible()
  await expect(page.getByRole('link', { name: 'AgentsKit Chat overview' })).toHaveAttribute('href', 'https://www.agentskit.io/docs/chat')
  await input.fill('unknown topic')
  await page.getByRole('button', { name: 'Send', exact: false }).click()
  await expect(page.getByText('No grounded sources were found for this question.')).toBeVisible()
})
