import { ApprovalRequestPropsSchema, ButtonGroupPropsSchema, ConfirmationPropsSchema, ErrorNoticePropsSchema, FileAttachmentPropsSchema, FormPropsSchema, LinkCardPropsSchema, ProgressPropsSchema, SourceListPropsSchema, TablePropsSchema, ToolCallPropsSchema, createComponentInteraction, resolveComponentFallback, resolveComponentFrame, type ComponentManifest } from '@agentskit/chat'
import type { ComponentInteractionEvent, ComponentRenderFrame } from '@agentskit/chat/protocol'
import { defineComponent, h, reactive, type PropType, type VNode } from 'vue'

export interface StandardComponentProps { readonly frame: ComponentRenderFrame; readonly manifest: ComponentManifest; readonly onInteract: (event: ComponentInteractionEvent) => void; readonly disabled?: boolean }

export const StandardComponent = defineComponent({
  name: 'AgentsKitStandardComponent',
  props: { frame: { type: Object as PropType<ComponentRenderFrame>, required: true }, manifest: { type: Object as PropType<ComponentManifest>, required: true }, onInteract: { type: Function as PropType<(event: ComponentInteractionEvent) => void>, required: true }, disabled: Boolean },
  setup(props) {
    const values = reactive<Record<string, string | boolean>>({})
    const emit = (event: string, value?: unknown): void => props.onInteract(createComponentInteraction(props.frame, props.manifest, event, value))
    return (): VNode | null => {
      if (!resolveComponentFrame(props.frame, props.manifest).ok || props.frame.componentKey === 'choice-list') return null
      const key = props.frame.componentKey
      if (key === 'button-group') { const item = ButtonGroupPropsSchema.parse(props.frame.props); return h('fieldset', { 'aria-label': item.label, 'data-ak-component': key }, [h('legend', item.label), ...item.buttons.map(button => h('button', { type: 'button', disabled: props.disabled || button.disabled, onClick: () => emit('select', button.id) }, button.label))]) }
      if (key === 'form') { const item = FormPropsSchema.parse(props.frame.props); return h('form', { 'aria-label': item.title ?? 'Form', 'data-ak-component': key, onSubmit: (event: Event) => { event.preventDefault(); emit('submit', { ...values }) } }, [...(item.title ? [h('h3', item.title)] : []), ...item.fields.map(field => h('label', [field.label, field.type === 'select' ? h('select', { required: field.required, disabled: props.disabled, value: values[field.id] ?? '', onInput: (event: Event) => { if (event.target instanceof HTMLSelectElement) values[field.id] = event.target.value } }, [h('option', { value: '', disabled: true }, 'Select…'), ...(field.options?.map(option => h('option', { value: option.id }, option.label)) ?? [])]) : h('input', { type: field.type, required: field.required, disabled: props.disabled, placeholder: field.placeholder, onInput: (event: Event) => { if (event.target instanceof HTMLInputElement) values[field.id] = field.type === 'checkbox' ? event.target.checked : event.target.value } })])), h('button', { type: 'submit', disabled: props.disabled }, item.submitLabel)]) }
      if (key === 'confirmation') { const item = ConfirmationPropsSchema.parse(props.frame.props); return h('section', { 'aria-label': item.title, 'data-ak-component': key }, [h('h3', item.title), h('p', item.message), h('button', { disabled: props.disabled, onClick: () => emit('confirm') }, item.confirmLabel), h('button', { disabled: props.disabled, onClick: () => emit('cancel') }, item.cancelLabel)]) }
      if (key === 'progress') { const item = ProgressPropsSchema.parse(props.frame.props); return h('div', { 'data-ak-component': key }, [h('label', [item.label, h('progress', { max: 100, value: item.value })]), item.status ? h('p', item.status) : null]) }
      if (key === 'source-list') { const item = SourceListPropsSchema.parse(props.frame.props); return h('section', { 'data-ak-component': key }, [h('h3', item.label), h('ul', item.sources.map(source => h('li', [source.url ? h('a', { href: source.url, onClick: (event: Event) => { event.preventDefault(); emit('open', source.id) } }, source.title) : source.title, source.snippet ? h('p', source.snippet) : null])))]) }
      if (key === 'link-card') { const item = LinkCardPropsSchema.parse(props.frame.props); return h('a', { href: item.href, 'data-ak-component': key, onClick: (event: Event) => { event.preventDefault(); emit('open', item.href) } }, [h('strong', item.title), item.description, item.label]) }
      if (key === 'error-notice') { const item = ErrorNoticePropsSchema.parse(props.frame.props); return h('section', { role: 'alert', 'data-ak-component': key }, [h('strong', item.title), h('p', item.message), item.code ? h('code', item.code) : null, item.retryLabel ? h('button', { disabled: props.disabled, onClick: () => emit('retry') }, item.retryLabel) : null]) }
      if (key === 'tool-call') { const item = ToolCallPropsSchema.parse(props.frame.props); return h('section', { role: 'status', 'data-ak-component': key }, [h('strong', item.name), h('span', item.status), item.arguments ? h('pre', JSON.stringify(item.arguments, null, 2)) : null, item.result === undefined ? null : h('pre', JSON.stringify(item.result, null, 2))]) }
      if (key === 'approval-request') { const item = ApprovalRequestPropsSchema.parse(props.frame.props); return h('section', { 'aria-label': item.title, 'data-ak-component': key }, [h('h3', item.title), h('p', item.description), h('button', { disabled: props.disabled, onClick: () => emit('approve') }, item.approveLabel), h('button', { disabled: props.disabled, onClick: () => emit('deny') }, item.denyLabel)]) }
      if (key === 'table') { const item = TablePropsSchema.parse(props.frame.props); return h('table', { 'data-ak-component': key }, [h('caption', item.caption), h('thead', h('tr', item.columns.map(column => h('th', { scope: 'col' }, column.label)))), h('tbody', item.rows.map(row => h('tr', item.columns.map(column => h('td', String(row[column.key] ?? ''))))))]) }
      if (key === 'file-attachment') { const item = FileAttachmentPropsSchema.parse(props.frame.props); return h('article', { 'data-ak-component': key }, [h('strong', item.name), h('span', item.mimeType), item.sizeBytes === undefined ? null : h('span', `${item.sizeBytes} bytes`), item.url ? h('a', { href: item.url, onClick: (event: Event) => { event.preventDefault(); emit('open', item.url) } }, 'Open') : null]) }
      return h('p', { 'data-ak-component-fallback': '' }, resolveComponentFallback(props.frame, props.manifest) ?? '')
    }
  },
})
