import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { evaluateConformance, formatFinding, readJson, repositoryFileExists } from './conformance-lib.mjs'

const manifest = await readJson('conformance/manifest.json')
const { StandardComponentCatalog } = await import('../packages/chat/dist/index.js')
const findings = await evaluateConformance({ manifest, catalog: StandardComponentCatalog, loadJson: readJson, fileExists: repositoryFileExists })
if (findings.length > 0) {
  console.error(findings.map(formatFinding).join('\n'))
  process.exitCode = 1
} else {
  const renderers = manifest.renderers
  const requirements = manifest.requirements
  const rows = requirements.map(requirement => {
    const cells = renderers.map(renderer => {
      if (requirement.scope !== 'universal' && requirement.scope !== renderer.platform) return 'n/a'
      if (manifest.exceptions.some(item => item.renderer === renderer.id && item.requirement === requirement.id)) return 'exception'
      return renderer.evidence.some(item => item.requirement === requirement.id) ? 'yes' : 'no'
    })
    return `| ${requirement.label} | ${requirement.scope} | ${cells.join(' | ')} |`
  })
  const report = `# Renderer conformance matrix\n\nGenerated by \`pnpm conformance:report\`. Do not edit manually.\n\n| Requirement | Scope | ${renderers.map(item => item.id).join(' | ')} |\n|---|---|${renderers.map(() => '---').join('|')}|\n${rows.join('\n')}\n`
  const reportPath = resolve('docs/conformance/matrix.generated.md')
  if (process.argv.includes('--write')) await writeFile(reportPath, report)
  if (process.argv.includes('--check')) {
    const current = await readFile(reportPath, 'utf8').catch(() => '')
    if (current !== report) {
      console.error('[AKC_REPORT_STALE] — Run pnpm conformance:report and commit the generated matrix.')
      process.exitCode = 1
    }
  }
  if (process.exitCode === undefined) console.log(`Conformance PASS: ${renderers.length} renderers, ${requirements.length} requirements.`)
}
